model = Sequential()
model.add(LSTM(24, input_shape=(X.shape[1], X.shape[2]), return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(200), return_sequences=True)
model.add(Dropout(0.3)
model.add(LSTM(150))
model.add(Dropout(0.1))
model.add(Dense(y.shape[1], activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam')