name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.5.6 black==24.8.0

      - name: Check formatting with Black
        run: black --check --line-length 100 .

      - name: Lint with Ruff
        run: ruff check .
